name: Android CI Апончук

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Апончук
      # Ми додаємо --stacktrace, щоб у разі помилки ви бачили повний лог
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        # Використовуємо зірочки, щоб GitHub сам знайшов APK, де б він не лежав
        path: "**/build/outputs/apk/debug/*.apk"
