name: Android CI Апончук

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      # Вказуємо шлях саме до файлу всередині папки myapplication
      run: chmod +x ./myapplication/gradlew

    - name: Build with Gradle Апончук
      # Цей рядок каже системі зайти в папку myapplication перед збіркою
      working-directory: ./myapplication
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        # Використовуємо маску, щоб знайти APK у будь-якій підпапці
        path: "**/build/outputs/apk/debug/*.apk"
